# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_cards.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../00_cards.ipynb 3
class Card:
    "A playing card"
    def __init__ (self, 
                  suit: int, # An index into suits
                  rank: int): # An index into ranks
        self.suit,self.rank = suit,rank
    def __str__ (self): return f"{self.suit}-{self.rank}"
    __repr__ = __str__
