# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../01_deck.ipynb 4
class Deck:
    def __init__ (self, n):
        self.deck = []
        for k in range(n):
            self.deck.append (Card (suit=k, rank=3))
